dominodatalab/distributed-compute-operator

.codecov.yml

Files generated by kubebuilder make targets should not be evaluated.

Ignores coverage analysis of generated files

---

.github/workflows/go.yml
.gitignore
.goreleaser.yml
scripts/release.sh

Leveraging [goreleaser](https://goreleaser.com) to generate release artifacts and publish them as a Github release.

Add more-refined release process

---

pkg/crd/crd.go
pkg/crd/crd_test.go

Both operations were happening subsequently because the checks were incorrect.

Removes CRD create/update bug

---

scripts/development.sh

We're not building an image with the "ghcr.io" prefix so we should remove this default.
/cc @ddl-audi

Sets registry to blank during dev deployment

---

Makefile
api/v1alpha1/webhook_suite_test.go
config/crd/bases/distributed-compute.dominodatalab.com_rayclusters.v1beta1.yaml
config/crd/bases/distributed-compute.dominodatalab.com_sparkclusters.v1beta1.yaml
config/crd/embed.go
controllers/suite_test.go
deploy/helm/distributed-compute-operator/Chart.yaml
deploy/helm/distributed-compute-operator/templates/_helpers.tpl
deploy/helm/distributed-compute-operator/templates/webhook-configuration-mutating.yaml
deploy/helm/distributed-compute-operator/templates/webhook-configuration-validating.yaml
go.mod
pkg/crd/crd.go
pkg/crd/crd_test.go
pkg/crd/v1beta1.go
test/test.go

- relaxes `kubeVersion` constraint to allow deployment to v1.15 clusters
- supports `admissionregistration.k8s.io/v1beta1` API version so that mutating and validating webhook configurations can be used in v1.15 clusters
- Generates CRDs in both `v1` and `v1beta1` formats
- CRD apply/delete logic branches based on retrieved K8s version (i.e. if version is >= 1.1.6, use V1 API, else use V1Beta1)

Compat changes

---

.github/workflows/go.yml

In response to recent Codecov security breach, all existing credentials were delete and re-created with the following changes:
- Leverages new, limited bot PAT for GHCR registry access ( we should be able to use a short-lived `GITHUB_TOKEN` for access according to the docs but I haven't had any success there; will follow up with a separate test to try and make this work ).
- Uses dedicated and limited GCR credentials for DCO chart storage.
Configuration happened behind the scenes so there are no real appreciable changes to the code.

Updating CI security

---

deploy/helm/distributed-compute-operator/templates/deployment.yaml
deploy/helm/distributed-compute-operator/templates/networkpolicy.yaml
deploy/helm/distributed-compute-operator/values.yaml

- updates network policy metrics port
- adds prometheus annotations to operator pods
- adds `podLabels' value for added configurability

Exposing DCO metrics to metric consumers

---

deploy/helm/distributed-compute-operator/templates/deployment.yaml
deploy/helm/distributed-compute-operator/values.yaml

Allow cluster-wide pod priority & preemption settings (though it likely won't impact DCO much).

helm chart: support priority class name setting

---

api/v1alpha1/raycluster_webhook.go
api/v1alpha1/raycluster_webhook_integration_test.go
pkg/resources/ray/statefulset.go

To enable Istio for Ray, the Distributed Compute Operator replaces random worker ports with static ones and defaults to 5 worker ports.  This means that only up to 5 worker processes are allowed per worker pod.  This causes Ray programs to fail if they try to schedule more than 5 worker processes based on the resource requirements and the amount of cpu/gpu available in the hardware tiers.
https://github.com/cerebrotech/domino/pull/24018 addresses this by configuring the worker port list to 100 ports by default (worker port range configurable in Central Config) across all deployments.
For non-Istio deployments, we should not specify any static worker ports at all (which is only required for Istio deployments). 
- Nucleus will configure `spec.workerPorts` for Istio deployments only
- Remove …

PLAT-2322: Specify worker-port-list only if worker ports are defined

---

pkg/resources/ray/service.go
pkg/resources/ray/service_test.go

The general compute cluster rules don't support request upgrading. The dask dashboard requires http request upgrading, because it uses websockets (the rules work for the dask dashboard otherwise, AFAICT).
However, proxy passing these headers in the nginx rules makes istio unable to proxy requests to the ray dashboard. Even if the connection and upgrade headers are correct for normal http requests, istio cannot find a place to send them.
This breaks viewing of the ray dashboard on istio deployments, because requests to the ray dashboard are proxied using the general compute cluster rules. We need these rules to support the dask dashboard (these changes: https://github.com/cerebrotech/charts/pull/874). Therefore, we must make it so that the ray dashboard is viewable at all times, even when …

Rename http-dashboard to tcp-dashboard, so that istio can proxy requests with Upgrade and Connection headers on them

---

api/v1alpha1/sparkcluster_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/distributed-compute.dominodatalab.com_sparkclusters.v1beta1.yaml
config/crd/bases/distributed-compute.dominodatalab.com_sparkclusters.yaml
config/samples/distributed-compute_v1alpha1_sparkcluster.yaml
pkg/resources/spark/configmap.go
pkg/resources/spark/horizontalpodautoscaler.go
pkg/resources/spark/networkpolicy.go
pkg/resources/spark/podsecuritypolicy.go
pkg/resources/spark/service.go
pkg/resources/spark/serviceaccount.go
pkg/resources/spark/spark.go
pkg/resources/spark/statefulset.go

Spark services and network policies are missing `dominodatalab.com` labels.

Adding global labels to DCO Spark

---

pkg/cluster/dask/horizonalpodautoscaler.go
pkg/resources/ray/horizontalpodautoscaler.go
pkg/resources/ray/horizontalpodautoscaler_test.go
pkg/resources/spark/horizontalpodautoscaler.go
pkg/resources/spark/horizontalpodautoscaler_test.go

Autoscaling `AverageCPUUtilization` was previously an optional value, and had been made mandatory through recent changes. This fix converts it back into an optional value.
Tested against my local.

Fix Autoscaling AverageCPUUtilization

---

pkg/resources/spark/service.go
pkg/resources/spark/service_test.go
scripts/development.sh

Spark workers need to have the `block-manager` port exposed. 
This PR prefixes all Spark service ports with `tcp-` to force Istio to use `TCP`, as well as adds the `block-manager` port to the Spark worker service.
This PR was successfully tested on a deployment using the following script:
```
def install_pyspark():
import importlib.util
if importlib.util.find_spec('pyspark') is None:
import subprocess
print("Installing PySpark...")
subprocess.run(['pip', 'install', 'pyspark==3.1.1'])
print("PySpark successfully installed!")
install_pyspark()
import pyspark
sc = pyspark.SparkContext()
words = ['cat', 'elephant', 'rat', 'rat', 'cat']
wordRdd = sc.parallelize(words, 4)
pairRdd = wordRdd.map(lambda word: (word, 1))
counts = pairRdd.reduceByKey(lambda a, b: a + b)
print(counts.collect())
```

Fix Spark/Istio ports

---

.codecov.yml
.golangci.yml
api/v1alpha1/common.go
api/v1alpha1/daskcluster_types.go
api/v1alpha1/daskcluster_webhook.go
config/crd/bases/distributed-compute.dominodatalab.com_daskclusters.v1beta1.yaml
config/crd/bases/distributed-compute.dominodatalab.com_daskclusters.yaml
pkg/cluster/dask/clusterstatusupdate.go
pkg/cluster/dask/dask_test.go
pkg/cluster/dask/networkpolicy.go
pkg/cluster/dask/networkpolicy_test.go
pkg/cluster/dask/rbac_test.go
pkg/cluster/dask/service_test.go
pkg/cluster/dask/serviceaccount.go
pkg/cluster/dask/serviceaccount_test.go
pkg/controller/components/clusterstatusupdate.go

Testing was initially performed with a single worker and missed the requirement for worker-to-worker communication on port 3000. Also opens open up worker dashboard port (8787) to client-labeled pods since the _scheduler-delegated worker dashboards_ does not work as originally expected.
- Builds and adds canonical image url to status
- Adds extra printer columns to `kubectl get dask`

Fixes Dask network policy ingress rules

---

cmd/start.go
deploy/helm/distributed-compute-operator/templates/clusterrole.yaml
deploy/helm/distributed-compute-operator/templates/clusterrolebinding.yaml
deploy/helm/distributed-compute-operator/templates/deployment.yaml
deploy/helm/distributed-compute-operator/values.yaml
pkg/manager/config.go
pkg/manager/manager.go

This does not require the application to be re-deployed but does allow us the ability the move the DCO into a different namespace. I think that operationally this design makes more sense since DCO is more of a cluster component.

Allows dco to process CRs in other namespaces

---

pkg/resources/ray/service.go
pkg/resources/ray/service_test.go

the name needs to be prefixed with "tcp-" otherwise Istio will give you
the business.

reverts change to ray client service dashboard port

---

deploy/helm/distributed-compute-operator/templates/clusterrole.yaml

It looks to me like this is the only missing perm - when I add it, I don't see any errors on mpicluster CR delete. But if we are deleting the service/endpoint then we need to add that too.

Add delete permission to statefulsets in dco clusterrole

---

dockerfiles/rsyncd.conf

Add imported module to rsyncd.conf to sync /mnt/imported
https://dominodatalab.atlassian.net/browse/DOM-36776

[DOM-36776] Add imported module to rsyncd.conf

---

dockerfiles/mpi-worker-start.sh

This 'dynamically' adjusts the user we create for the permissions on k8s-mounted file systems. It does this by adding our user to all of the non-root groups to which the container-user (root in our current setup) belongs

DOM-37092 add groups from initial user to domino user

---

deploy/helm/distributed-compute-operator/values.yaml

Undoing our floating-main development approach

Restore pull policy to 'if not present'

---

controllers/mpicluster_controller.go
pkg/cluster/mpi/istiopeerauthentication.go

When Istio injection is disabled in the cluster in an Istio-enabled deployment, the workers cannot communicate back to the client which still has an Istio sidecar expecting mTLS. 
We detect this and create a PERMISSIVE PeerAuthentication for the _client_ to allow this communication.

Create PeerAuthentication for cluster client when Istio disabled

---

dockerfiles/mpi-init.Dockerfile
dockerfiles/mpi-sync.Dockerfile

* We need to update the base Debian image tag for `*-mpi-*` images to bring in OS lib updates with security fixes from upstream.
* these images need to be updated as part of the [release OSRP Process](https://dominodatalab.atlassian.net/wiki/spaces/ENG/pages/1938522147/OSRP+Process) going forward and we need this for the currently ongoing 5.1.3 release.
* More context: [RM-1305](https://dominodatalab.atlassian.net/browse/RM-1305)
* Update the base Debian image tag to `quay.io/domino/debian:10.11-20220520-1846`, which includes updated OS libs from upstream Debian's package manager.

RM-1305 Update debian OS libs in MPI images

---

dockerfiles/mpi-init.Dockerfile
dockerfiles/mpi-sync.Dockerfile

Link to JIRA: https://dominodatalab.atlassian.net/browse/RM-1130
Updated the 2nd order images for OSRP 5.2.0. Below is the build-images run from where new image tag is copied:
https://app.circleci.com/pipelines/github/cerebrotech/build-images/2205/workflows/1ac63d46-589f-40ca-a47b-dca8c584b607/jobs/166721

RM-1130 Updated 2nd order Image for OSRP 5.2.0

---

dockerfiles/mpi-init.Dockerfile
dockerfiles/mpi-sync.Dockerfile

Link to JIRA: https://dominodatalab.atlassian.net/browse/RM-1491
Updated the 2nd order images for OSRP 5.2.1. Below is the build-images run from where the new image tag is copied:
https://app.circleci.com/pipelines/github/cerebrotech/build-images/2276/workflows/19404c9f-a07e-4337-a1f5-ff03a41be00a/jobs/175566?invite=true#step-102-7

RM-1491 Updated 2nd order image for OSRP 5.2.1

---

.github/workflows/go.yml
Makefile
scripts/release/helm.sh

Helm 3.7 changed the default chart format when publishing to an OCI repo. This is backwards-incompatible with Helm < 3.7, so we've been publishing using 3.6 for now until we can transition fully to Helm >= 3.7.

bump helm to 3.9.3 to publish in the new OCI format

---

dockerfiles/mpi-init.Dockerfile
dockerfiles/mpi-sync.Dockerfile

Link to JIRA: https://dominodatalab.atlassian.net/browse/RM-1617
Link to build-image CI where the new tag is built and updated here:
https://app.circleci.com/pipelines/github/cerebrotech/build-images/2450/workflows/447df1dc-f7d3-4c65-bc48-42548767ec66/jobs/194066
We have updated the debian image tag as per [OSRP process](https://dominodatalab.atlassian.net/wiki/spaces/ENG/pages/1938522147/OSRP+Process) for 5.2.2.

RM-1617 Updated debian 10 image tag for OSRP 5.2.2

---

dockerfiles/mpi-init.Dockerfile
dockerfiles/mpi-sync.Dockerfile

Link to Jira: https://dominodatalab.atlassian.net/browse/RM-1554
Update of Debian 10 image for OSRP 5.3.0 as per [OSRP process](https://dominodatalab.atlassian.net/wiki/spaces/ENG/pages/1938522147/OSRP+Process)
Link to the build-image Circle CI run: https://app.circleci.com/pipelines/github/cerebrotech/build-images/2575/workflows/2e7ed326-4ef0-4948-8235-eacce1cfab0a/jobs/208087

RM-1554 Updated debian 10 image tag for OSRP 5.3.0

---

dockerfiles/mpi-init.Dockerfile
dockerfiles/mpi-sync.Dockerfile

* Updates Debian 10 image for 5.3.0  OSRP  -- only the *-MPi-* images are affected.
Co-authored-by: Keshav Ray <keshavray@ScaleWorx.local>

RM-1554 Updated debian 10 image tag for OSRP 5.3.0 (#122)

---

api/v1alpha1/common_types.go
api/v1alpha1/daskcluster_webhook.go
api/v1alpha1/raycluster_webhook.go
api/v1alpha1/raycluster_webhook_integration_test.go
api/v1alpha1/sparkcluster_webhook.go
api/v1alpha1/sparkcluster_webhook_integration_test.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/distributed-compute.dominodatalab.com_daskclusters.yaml
config/crd/bases/distributed-compute.dominodatalab.com_mpiclusters.yaml
config/crd/bases/distributed-compute.dominodatalab.com_rayclusters.yaml
config/crd/bases/distributed-compute.dominodatalab.com_sparkclusters.yaml
config/samples/distributed-compute_v1alpha1_daskcluster.yaml
config/samples/distributed-compute_v1alpha1_raycluster.yaml
deploy/helm/distributed-compute-operator/dco-values.yaml
pkg/cluster/dask/dask_test.go
pkg/cluster/dask/networkpolicy.go
pkg/cluster/dask/networkpolicy_test.go
pkg/resources/ray/networkpolicy.go
pkg/resources/ray/networkpolicy_test.go
pkg/resources/spark/networkpolicy.go
pkg/resources/spark/networkpolicy_test.go

Currently the network policy allowing access to the cluster ui utilizes the hardcoded value `domino-platform` as it's namespace selector, which does not work in remote data planes where there is no platform namespace. This PR allows for setting the namespace selector dynamically instead.
https://dominodatalab.atlassian.net/browse/HBD-505

HBD-505 Dynamically set dashboard namespace selector

---

deploy/helm/distributed-compute-operator/values.yaml

All charts must have a pod security context defined. It must include runAsNonRoot, runAsUser and seLinuxOption.

PLAT-5844: Explicit Pod Security Contexts

---

.github/workflows/go.yml
.golangci.yml
Dockerfile
Makefile
api/v1alpha1/groupversion_info.go
go.mod
go.sum

Update golang 1.17.1 → 1.19.3 to mitigate [CVE-2022-27664](https://nvd.nist.gov/vuln/detail/CVE-2022-27664).
Along the way, fixed a few minor issues accumulated over time, which prevented using the new version.

VULN-472 • Upgrade golang

---

Makefile
controllers/suite_test.go

https://dominodatalab.atlassian.net/browse/HBD-703
After upgrading to a newer version of k8s in the test environment, the DCO tests started failing. The root cause was that the test cluster has been shutting down too soon, before resources were finalized.
A recipe for this fix is from here: https://github.com/kubernetes-sigs/kubebuilder/pull/2379

HBD-703 • Cluster destroy failures (tests only)

---

.github/workflows/go.yml
Dockerfile
dockerfiles/mpi-init.Dockerfile
dockerfiles/mpi-sync.Dockerfile

[DOM-46931](https://dominodatalab.atlassian.net/browse/DOM-46931)
* update all images built as part of DCO to produce `arm64` variants as
well as `amd64`

DOM-46931: provide `arm64` variant of DCO image
